name: Test Tap Formula

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - macos-latest

    steps:
    - name: Install Formula
      run: |
        brew install awnion/tap/boost@1.83
        brew link --force --overwrite awnion/tap/boost@1.83

    - name: Test Formula
      run: |
        brew test awnion/tap/boost@1.83
